FROM graylog2/server

RUN wget -O /usr/share/graylog/plugin/graylog-plugin-mongodb-profiler-2.0.1.jar https://github.com/graylog-labs/graylog-plugin-mongodb-profiler/releases/download/2.0.1/graylog-plugin-mongodb-profiler-2.0.1.jar